%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-csm
Version:        1.0.2
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS csm package

License:        LGPL
URL:            http://censi.mit.edu/software/csm
Source0:        %{name}-%{version}.tar.gz

Requires:       gsl-devel
Requires:       ros-noetic-catkin
BuildRequires:  cmake
BuildRequires:  gsl-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This is a ROS 3rd-party wrapper (see REP-136 for more detail) of Andrea Censi's
CSM package. From the official website: The C(anonical) Scan Matcher (CSM) is a
pure C implementation of a very fast variation of ICP using a point-to-line
metric optimized for range-finder scan matching. It is robust enough to be used
in industrial prototypes of autonomous mobile robotics, for example at Kuka. CSM
is used by a variety of people, though it is hard to keep track because of the
open source distribution, especially as packaged in ROS. If you use this
software for something cool, let me know.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed Jun 03 2020 Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp> - 1.0.2-2
- Autogenerated by Bloom

* Sun May 31 2020 Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp> - 1.0.2-1
- Autogenerated by Bloom

