Name:           ros-jade-csm
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS csm package

Group:          Development/Libraries
License:        LGPL
URL:            http://censi.mit.edu/software/csm
Source0:        %{name}-%{version}.tar.gz

Requires:       gsl
BuildRequires:  cmake
BuildRequires:  gsl

%description
This is a ROS 3rd-party wrapper (see REP-136 for more detail) of Andrea Censi's
CSM package. From the official website: The C(anonical) Scan Matcher (CSM) is a
pure C implementation of a very fast variation of ICP using a point-to-line
metric optimized for range-finder scan matching. It is robust enough to be used
in industrial prototypes of autonomous mobile robotics, for example at Kuka. CSM
is used by a variety of people, though it is hard to keep track because of the
open source distribution, especially as packaged in ROS. If you use this
software for something cool, let me know.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri Dec 18 2015 Isaac I.Y. Saito <130s@2000.jukuin.keio.ac.jp> - 1.0.2-0
- Autogenerated by Bloom

